import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import styles from '../styles/Home.module.css';


export default function Home() {
  const [num1, setNum1] = useState(0);
  const [num2, setNum2] = useState(0);
  const [num3, setNum3] = useState(0);
  const [result, setResult] = useState(0);
  const [fetched, setFetched] = useState('');
  const add = () => {
    setResult(num1 + num2 + num3);
    fetch('/api/hello')
      .then((res) => res.json())
      .then((data) => {
        setFetched(data)
      })
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.result} data-testid='result'>
        {result}
      </div>
      <input
        type='text'
        className={styles.input}
        data-testid='num1'
        value={num1}
        onChange={(e) => setNum1(e.target.value)}
      />
      <input
        type='text'
        className={styles.input}
        data-testid='num2'
        value={num2}
        onChange={(e) => setNum2(e.target.value)}
      />
      <input
        type='text'
        className={styles.input}
        data-testid='num3'
        value={num3}
        onChange={(e) => setNum3(e.target.value)}
      />
      <button onClick={add} className={styles.button} data-testid='add'>
        Submit
      </button>
      <div className={styles.result} data-testid='fetched'>
        {fetched && fetched.map(data => <p>{data.commodity} from {data.country} at {data.variable_cost}</p>)}
      </div>
    </div>
  );
}
